language: python

python:
 - "2.7"
 cache: pip

before_install:
 - pip install -U pip

install:
 - pip install -r requirements.txt

before_script:
 - cd Tests/

script:
  - ./Integration_Test.py test
  - ./test_api.py test
  - ./Test_baseApi.py test