version: 2.7

orbs:
  python: circleci/python@0.2.7

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./Tests/test_baseApi.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
